name: Main

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: get ver
        run: |
          echo "$(grep -E '^is_sh_ver=' sing-box.sh)" >> $GITHUB_ENV
          echo "old=$(git tag --sort=-v:refname | head -n1)" >> $GITHUB_ENV
      # - name: test
      #   if: env.is_sh_ver == env.old 
      #   run: |
      #     echo not found new version.
      #     exit 1
      - name: tar
        run: tar zcvf code.tar.gz install.sh core.sh sing-box.sh src LICENSE README.md
      - name: release
        uses: softprops/action-gh-release@v1
        with:
          files: code.tar.gz
          tag_name: ${{ env.is_sh_ver }}
